spring.application.name=quizBank

# resources 폴더 아래에 schema.sql과 data.sql의 실행 모드
# always : 인메모리/외부 DB 상관없이 항상 실행, embedded : 인메모리 DB 사용할 때만 실행, never : 실행 안함
# 해당 프로퍼티를 제거하면 embedded로 작동함
spring.sql.init.mode=embedded

# H2 접속 정보
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true

# Supabase PostgreSQL 접속 정보
# 패스워드에 특수문자 포함되면 읽기 불가
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Brevo API 설정
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_EMAIL}
brevo.sender.name=${BREVO_NAME}
brevo.target.email=${BREVO_TARGET_EMAIL}
brevo.use=${BREVO_USE}